# Set sudo
sudo: false

# Set the build language to Python
language: python

# Set OS/Python testing configurations
matrix:
    include:
        - name: "Python 3.6 on Linux"
          os: linux
          python: 3.6
        - name: "Python 3.7 on Xenial Linux"
          os: linux
          python: 3.7
          dist: xenial

# Command to install dependencies
install:
  - pip install -r requirements.txt

# Command to run tests
script:
  - py.test --cov=pydeco --cov-config .coveragerc

# Push the code coverage results to codecov
after_success:
  - codecov